plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.hex8.ora.hardware'

def packageJson = new groovy.json.JsonSlurper().parseText(file('../package.json').text)
version = packageJson.version

android {
  namespace "com.hex8.ora.hardware"
  defaultConfig {
    versionCode 1
    versionName packageJson.version
    consumerProguardFiles 'proguard-rules.pro'
  }
  lintOptions {
    abortOnError false
  }
}
